// Auto-generated Lua resource bindings
//
// This module provides the infrastructure for automatic resource method binding.
// The actual bindings are generated by the build script.

// Include the generated code
include!(concat!(env!("OUT_DIR"), "/auto_bindings.rs"));
